# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 晨叶梦春的小屋
subtitle: 温馨和谐的小屋
description: Not for the best, just for the better.
keywords: '梦春, 梦春酱, 晨叶梦春, wuziqian211, YumeHaru, 211娘'
author: 晨叶梦春
language: zh-CN
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://www.yumeharu.top
root: /
permalink: /archives/:year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - emote/**/*
  - images/**/*
  - robots.txt

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: false
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude:
    - www.yumeharu.top
    - wuziqian211.top
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  auto_detect: false
  line_number: true
  line_threshold: 1
  tab_replace: '  '
  exclude_languages:
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  line_threshold: 1
  tab_replace: '  '

# Category & Tag
default_category: uncategorized
category_map:
  生活: life
  搞笑: funny
  日常: daily
  知识: knowledge
  野生技能协会: skill
tag_map:
  Blog: blog
  wuziqian211: wuziqian211
  梦春酱: yumeharu
  生草: grass
  网站: website
  翻译: translation
  谷歌: google
  评论: comments
  自动回复: auto-reply
  技术: technology
  用户列表: users-list

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next
theme_config:

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

archive_generator:
  enabled: true
  per_page: 0
  yearly: true
  monthly: true
  daily: true
  order_by: -date

symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false
  wpm: 275
  suffix: 'mins.'

search:
  path: search.xml
  field: all
  content: true
  format: striptags

server:
  port: 2111
  log: true
  ip: 0.0.0.0
  compress: true
  cache: false
  header: true
  serveStatic:
    extensions: false

nofollow:
  enable: true
  field: site
  exclude:
    - www.yumeharu.top
    - wuziqian211.top

markdown:
  preset: 'default'
  render:
    html: true
    xhtmlOut: true
    langPrefix: 'language-'
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  enable_rules:
  disable_rules:
  plugins:
  anchors:
    level: 2
    collisionSuffix: ''
    permalink: true
    permalinkClass: 'headerlink'
    permalinkSide: 'right'
    permalinkSymbol: ''
    case: 1
    separator: '-'

sitemap:
  path:
    - sitemap.xml
  template:
  template_txt:
  rel: true
  tags: true
  categories: true

related_posts:
  enabled: true
  enable_env_name:
  filter_threshold: 0.2
  related_count: 5
  weight:
    title: 0.05
    author: 0
    description: 0.05
    keywords: 0.01
    tags: 0.005
    categories: 0.005
    text: 1
  stemmers:
    - en
    - ru
  reserved:
    - asp.net
    - vs.net
    - ado.net
    - .net

minify:
  enable: true
  previewServer: true
  html:
    enable: true
  css:
    enable: true
    exclude:
      - '*.min.css'
  js:
    enable: true
    exclude:
      - '*.min.js'
  svg:
    enable: true
    include:
      - '*.svg'
      - '!*.min.svg'
    plugins:
      collapseGroups: false
      removeViewBox: false
  xml:
    enable: true
    include:
      - '*.xml'
      - '!*.min.xml'
  json:
    enable: true
    include:
      - '*.json'
      - '!*.min.json'
  gzip:
    enable: false
  brotli:
    enable: false
  zstd:
    enable: false
